# https://terraform-docs.io/user-guide/configuration/

settings:
  hide-empty: true

formatter: "markdown table"

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
